# Generated by Django 2.1.1 on 2018-09-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnslog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='recvdata',
            new_name='recvdate',
        ),
    ]
